version: '2'


services:
  eegnet:
    container_name: eegnet 
    image: appia/eegnet:latest 
    build: 
      context: ./
      dockerfile: ./Docker/Dockerfile 
    ports:
     - "6006:6006"
     - "8888:8888"
    volumes:
     - ./:/shared


